### ISSUE TITLE
Cut over DNS to new site

### ISSUE THREAD

**Issue by RyKilleen** [mutualaidphilly/mutual-aid-philly-sanity#27]

**Comment by RyKilleen** [comment]
@boblannon a quick question for you regarding Mutual Aid Philly's DNS:

1. Who's the DNS provider?
2. Do they support ANAME or ALIAS records?

When it comes time to cut over to the new site, we'll want to lower the TTL a few days in advance, and set an ALIAS record as follows:

> mutualaidphilly.com ALIAS mutual-aid-philly.netlify.app

I'm happy to own that work or leave it up to whoever has access!

**Comment by boblannon** [comment]
It's with iwantmyname, and I can set the alias up tomorrow

**Comment by RyKilleen** [comment]
Good to know! I don't think we're quite ready to cut over yet. I think the tech/content team can work to get a cut-over date, just wanted to get an understanding of the effort involved!

**Comment by RyKilleen** [comment]
Hi @boblannon! The time has come to set our sites on cutting over.

Can we lower the TTL in preparation, and collaborate on a time to cut over?

**Comment by boblannon** [comment]
Yep, sounds good to me.  Should I set the ALIAS as well?

**Comment by RyKilleen** [comment]
Not quite yet, I want to pick a time where we don't mind troubleshooting DNS problems 😄 

Tomorrow or Friday after 8pm works for me if you're around! I can take it over to slack so the team at large is privy to it as well.

**Comment by boblannon** [comment]
:white_check_mark: updated TTL to 60 for all records (they wouldn’t let me go lower than that)

**Comment by RyKilleen** [comment]
This is complete! Thanks for your help, @boblannon!
